---
title: "Project Portfolio Git"
author: "Himabindu"
date: "2023-03-17"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Package for loading breast cancer data
```{r}
#install.packages("mlbench")
library(mlbench)
```

# Read Data
```{r}
data(BreastCancer)
ls(BreastCancer)
```

# Libraries
```{r}
library(e1071)
library(klaR)
library(nnet)
library(MASS)
library(rpart)
library(randomForest)
```

# Partitioning the data and cleaning the missing values
```{r}
summary(BreastCancer)

BreastCancer <- na.omit(BreastCancer) 

BreastCancer$Id <- NULL 
head(BreastCancer)
str(BreastCancer)

# partition the data set for 80% training and 20% evaluation (adapted from ?randomForest)
set.seed(2)

ind <- sample(2, nrow(BreastCancer), replace = TRUE, prob=c(0.8, 0.2))

```

# Support Vector Machine
```{r}
mysvm <- svm(Class ~ ., BreastCancer[ind == 1,])
mysvm.pred <- predict(mysvm, BreastCancer[ind == 2,])
table(mysvm.pred,BreastCancer[ind == 2,]$Class)
```

# Naive bayes
```{r}
mynb <- NaiveBayes(Class ~ ., BreastCancer[ind == 1,])
mynb.pred <- predict(mynb,BreastCancer[ind == 2,])
head(mynb.pred$class)
table(mynb.pred$class,BreastCancer[ind == 2,]$Class)
str(mysvm.pred)
str(mynb.pred)
```

# Decision tree using rpart
```{r}
library(rpart)
mytree <- rpart(Class ~ ., BreastCancer[ind == 1,])
plot(mytree, cex = 0.7, margin = 0.1)
text(mytree, cex = 0.7, xpd = TRUE)
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer[ind == 2,],type="class")
table(mytree.pred,BreastCancer[ind == 2,]$Class)
```

# Regularised Discriminant Analysis
```{r}
myrda <- rda(Class ~ ., BreastCancer[ind == 1,])
myrda.pred <- predict(myrda, BreastCancer[ind == 2,])
table(myrda.pred$class,BreastCancer[ind == 2,]$Class)
```

# Random Forests
```{r}
myrf <- randomForest(Class ~ ., BreastCancer[ind == 1,])
myrf.pred <- predict(myrf, BreastCancer[ind == 2,])
head(myrf.pred)
table(myrf.pred, BreastCancer[ind == 2,]$Class)
```


# Combining the 5 classifiers results
```{r}
combine.classes<-data.frame(myrf.pred, mytree.pred,mysvm.pred, mynb.pred$class, myrda.pred$class)

head(combine.classes)
head(myrf.pred)
head(myrda.pred)
combine.classes$myrf.pred<-ifelse(combine.classes$myrf.pred=="benign", 0, 1)
combine.classes[,2]<-ifelse(combine.classes[,2]=="benign", 0, 1)
combine.classes[,3]<-ifelse(combine.classes[,3]=="benign", 0, 1)
combine.classes[,4]<-ifelse(combine.classes[,4]=="benign", 0, 1)
combine.classes[,5]<-ifelse(combine.classes[,5]=="benign", 0, 1)
#combine.classes[,6]<-ifelse(combine.classes[,6]=="benign", 0, 1)
#str(combine.classes)
combine.cl<-combine.classes[, -c(6,7)]

# Calculate row sums
majority.vote <- rowSums(combine.classes[, -c(6,7)])

#majority.vote=rowSums(combine.classes[,-c(7,8)])
head(majority.vote)
combine.classes[,6]<-rowSums(combine.classes[,-c(6,7)])
combine.classes[,7]<-ifelse(combine.classes[,6]>=4, "malignant", "benign")
str(combine.classes)
table(combine.classes[,7], BreastCancer[ind == 2,]$Class)

# Load the caret package
library(caret)

# Create a sample confusion matrix
confusion_matrix <- table(combine.classes[,7], BreastCancer[ind == 2,]$Class)

# Calculate accuracy, precision, and recall
accuracy <- sum(diag(confusion_matrix))/sum(confusion_matrix)
precision <- diag(confusion_matrix)/colSums(confusion_matrix)
recall <- diag(confusion_matrix)/rowSums(confusion_matrix)

# Print the results
cat(paste0("Accuracy: ", round(accuracy, 2), "\n"))
cat(paste0("Precision: ", paste(round(precision, 2), collapse = ", "), "\n"))
cat(paste0("Recall: ", paste(round(recall, 2), collapse = ", "), "\n"))


```




